### PR TITLE
fix: interact with Gist timer on main

### LINKED ISSUE #839: Crash in `Gist.invalidateTimer`
**SDK version:** 3.5.0 (though I believe also 3.6.0 – haven't shipped with that yet)

**Environment:** Production

**Are logs available?** 
No. But we do have a crash log:
```
OS Version: iOS 18.1.1 (22B91)
Report Version: 104

Exception Type: EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0 at 0x000000018a9fd0d4
Crashed Thread: 2

Application Specific Information:
Signal 5, Code 0

Thread 2 Crashed:
0   CoreFoundation                  0x30d7c30d4         CF_IS_OBJC
1   CoreFoundation                  0x30d7bcfe8         [inlined] CFRetain
2   CoreFoundation                  0x30d7bcfe8         CFRetain
3   CoreFoundation                  0x30d8532e4         CFRunLoopTimerInvalidate
4   Tolan                           0x202de5ae0         [inlined] Gist.invalidateTimer (Gist.swift:70)
5   Tolan                           0x202de5ae0         Gist.setupPollingAndFetch (Gist.swift:130)
6   Tolan                           0x202de57ac         closure in Gist.setUserToken (Gist.swift:103)
7   Tolan                           0x202df8c70         closure in InAppMessageStoreManager.fetchState (InAppMessageManager.swift:82)
8   libswift_Concurrency.dylib      0x32460d100         swift::runJobInEstablishedExecutorContext
```

No other threads are working within Gist or other CustomerIO code. Note that we're calling `identify(userId:traits:)` from a queue other than main.

**Describe the bug**
A crash sometimes occurs when a timer is invalidated within CustomerIO.

**To Reproduce**
Unknown. We're seeing a few of these crashes in the wild in recent-ish builds.

**Expected behavior**
CustomerIO does not crash

**Screenshots**
N/A

**Additional context**
I see the following code in `Gist.swift`:
```swift
        // Timer must be scheduled on the main thread
        threadUtil.runMain {
```

It looks like we're invalidating the timer on a queue other than main. We probably want to only talk to the timer on main...

### PR DESCRIPTION
**Pull request by dfed**
Attempts to resolve #839

Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/blob/develop/docs/dev-notes/GIT-WORKFLOW.md). 
- [ ] [Assign members of your team](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to review the pull request. 
- [ ] Wait for pull request status checks to complete. If there are problems, fix them until you see that [all status checks are passing](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsymfony.com%2Fdoc%2F4.3%2F_images%2Fdocs-pull-request-symfonycloud.png&f=1&nofb=1). 
- [ ] Wait until the pull request has been reviewed *and approved* by a teammate
- [ ] After code reviews are approved and you determine this PR is ready to merge, select *Squash and Merge* button on this screen, leave the title and description to the default values, then merge the PR.

### CODE REVIEW

File: Sources/MessagingInApp/Gist/Gist.swift [hunk 1]
```diff
@@ -67,8 +67,11 @@ class Gist: GistProvider {
     }
 
     private func invalidateTimer() {
-        queueTimer?.invalidate()
-        queueTimer = nil
+        // Timer must be scheduled or modified on main.
+        threadUtil.runMain {
+            queueTimer?.invalidate()
+            queueTimer = nil
```
Comment (dfed) [inline Sources/MessagingInApp/Gist/Gist.swift:73]:
```suggestion
            self.queueTimer?.invalidate()
            self.queueTimer = nil
```

**Comment by mads-frameo** [comment]
Just add to support for prioritising the fix, we are also seeing the same crash for some of our users.

**Review by Shahroz16 — APPROVED** [review]
